#!/usr/bin/env bash
# a Bash script that will display information about subdomains

dig_web() {
	dig "$2.$1" | awk -v sub_dom="$2" '/\S+\s+[0-9]+\s+IN/{
		printf "The subdomain %s is a %s record and points to %s\n", sub_dom, $4, $5
	}'
}

if [ "$2" ]; then
	dig_web "$1" "$2"
else
	dig_web "$1" 'www'
	dig_web "$1" 'lb-01'
	dig_web "$1" 'web-01'
	dig_web "$1" 'web-02'
fi
