#!/usr/bin/env bash

ac=$#

if (( ac > 2 )); then
	file=$1
	ip=$2
	user=$3
	
	if (( ac == 4 )); then
		key=$4
	
		scp -i "$key" -o StrictHostKeyChecking=No "$file" "$user@$ip:~/"
	elif (( ac == 3)); then
		scp -o StrictHostKeyChecking=No "$file" "$user@$ip:~/"
	fi
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi
