#!/usr/bin/env bash

ac=$#

if (( ac == 4 )); then
	file=$1
	ip=$2
	user=$3
	key=$4

	scp -i "$key" -o StrictHostKeyChecking=No "$file" "$user@$ip:~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi
