#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument

IPADDR=$1

if [ "$IPADDR" ]; then
	ping -c 5 "$IPADDR"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
