#!/usr/bin/env bash
# a bash script that traps signals

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap "echo Y U no love me?! && exit" SIGINT
	trap "echo I hate the kill command && rm -f /var/run/myscript.pid && exit" SIGTERM
	trap "rm -f /var/run/myscript.pid && exit" SIGQUIT
	sleep 2
done
