#!/usr/bin/env bash
#!/usr/bin/env bash
# a bash script that displays:
# To infinity and beyond indefinitely
# with a `sleep 2` inbetween each iteration
# I a am invisible!!! when receiving a SIGTERM signal

a=1
b=2
while [ $a -le $b ];
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invisible!!!" SIGTERM
done
