#!/usr/bin/env bash

f_name=$1

if [ -f "$f_name" ]
then
	echo 'file exists...'
else
	if [ "$f_name" ]
	then
		touch = $f_name
		chmod u+x $f_name
		echo '#!/usr/bin/env bash' > $f_name
		vi $f_name
	else
		echo "Oops! No filename input?"
		echo "command usage: ./bsh [filename]"
	fi
fi
