#!/usr/bin/env bash
# manipulates etc/passwd file into a text

while read -r line; do
	printf "The user %s " "$(echo "$line" | cut -d ':' -f 1)"
	printf "is a part of the %s, " "$(echo "$line" | cut -d ':' -f 4)"
	printf "lives in %s " "$(echo "$line" | cut -d ':' -f 6)"
	printf "and rides %s. " "$(echo "$line" | cut -d ':' -f 7)"
	printf "%s's place is protected by the passcode " "$(echo "$line" | cut -d ':' -f 3)"
	printf "%s, more info about the user here:" "$(echo "$line" | cut -d ':' -f 2)"
	printf "%s" "$(echo "$line" | cut -d ':' -f 5)"
	echo
done < /etc/passwd

# The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
