#!/usr/bin/env bash
# a bash script that displays Best SChool 10 times using while loop

i=1

while (( i<=10 ))
do
	if (( i==4 ))
	then
		echo 'bad luck'
	elif (( i==8 ))
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	i=$(( ++i ))
done
