#!/usr/bin/env bash
# prints nunber 1-20 

i=1
while (( i <= 20))
do
	echo "$i"
	if (( i == 4 ))
	then
		echo bad luck from china
	elif (( i == 9 ))
	then
		echo bad luck from japan
	elif (( i == 17 ))
	then
		echo bad luck from italy
	fi
	i=$(( i + 1 ))
done
