#!/usr/bin/env bash
# a bash script that displays Best SChool 10 times using while loop

i=0

while (( i<=20 ))
do
	case $i in
		4)
			echo 'bad luck from China'
			;;
		9)
			echo 'bad luck from Japan'
			;;
		17)
			echo 'bad luck from Italy'
			;;
		*)
			echo 'Best School'
			;;
	esac
	i=$(( ++i ))
done
