#!/usr/bin/env bash
# a bash script that displays Best SChool 10 times using while loop

i=1

while (( i<=20 ))
do
	case $i in
		4)
			echo "$i"
			echo 'bad luck from China'
			;;
		9)
			echo "$i"
			echo 'bad luck from Japan'
			;;
		17)
			echo "$i"
			echo 'bad luck from Italy'
			;;
		*)
			echo "$i"
			;;
	esac
	i=$(( ++i ))
done
