#!/usr/bin/env bash
# a bash script that displays the content of the current directory in a list
# format.

for content in *; do
	flag=0
	if [[ "$string" == *-* ]]; then
		for (( i=0; i<${#content}; i++)); do
			if [ "${content:$i:1}" == "-" ]; then
				flag=1
				i=$(( i + 1 ))
			fi
			if (( flag == 1 )); then
				printf "%s" "${content:$i:1}"
			fi
		done
		printf "\n"
	else
		echo $content
	fi

done
