#!/usr/bin/env bash
# a bash script that displays the content of the current directory in a list
# format.

dash=-
for content in "$1"*;
do
	flag=0
#	echo "$content"
	for char in $content;
	do
		if [ "$char" = "$dash" ]
		then
			flag=1
		fi
		if (( flag == 1))
		then
			printf "%s" "$char"
		fi
	done
	echo
done
echo $flag
