#!/usr/bin/env bash
# configures a server to allow connection from 
# only port 22, 443, and 80

sudo ufw default deny incoming
sudo ufw default allow 344
sudo ufw default allow 22
sudo ufw default allow 80
