#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

sudo sed -i.new 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i '/localhost/a 8.8.8.8	facebook.com' /etc/hosts
sudo mv /etc/hosts.new /etc/hosts
#sudo mv new /etc/hosts
#rm host
