#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

sudo sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > host
sed  '/localhost/a 8.8.8.8	facebook.com' host  > new
sudo mv new /etc/hosts
rm host
