#!/usr/bin/env bash
# Bash script that configures an Ubuntu server

sudo sed  's/127.0.0.1/127.0.0.2/g' /etc/hosts > hosts
sed -i.new  '/localhost/a 8.8.8.8	facebook.com' hosts
sudo echo “$(cat hosts.new)” > /etc/hosts
