#!/usr/bin/env bash
# configures a container to run nginx as nginx(user) and not root

# grant permission and ownership to nginx user
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf

# stop the apache webserver
pkill -f apache2

# configure ipv4 port
new_string="listen 8080 default_server;"
sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

# configure ipv6 port
new_string="listen \[::\]:8080 default_server ipv6only=on;"
sed -i "s/listen \[::\]:80 default_server ipv6only=on;/$new_string/" /etc/nginx/sites-available/default

sudo -u nginx service nginx start
