#!/usr/bin/env bash
# configures a container to run nginx as nginx(user) and not root
chmod 600 /etc/nginx/nginx.conf
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -f apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
